<template>
	<transition name="fade-top" mode="out-in">
		<div class="wallet-step wallet-mode" v-if="step === 'pickMode'" key="pickMode">
			<div class="create-wallet-button" @click="step = 'create'">
				<div class="button-icon"><icon icon="plus" /></div>
				<div class="button-title">New Wallet</div>
				<p>Generates a new wallet seed in the browser. Transactions can be sent and received.</p>
			</div>
			<div class="create-wallet-button" @click="step = 'recover'">
				<div class="button-icon"><icon icon="redo" /></div>
				<div class="button-title">Recover Wallet</div>
				<p>Recovers an existing wallet from a 29 word seed. Transactions can be sent and received.</p>
			</div>
			<div :class="hardwareBtnClasses" @click="onClickLedgerSupport('ledger')">
				<div class="button-icon"><icon :icon="['fab', 'usb']" /></div>
				<div class="button-title">Ledger Wallet</div>
				<p v-if="ledgerSupported">Creates a new hardware backed wallet. All transactions must be signed by the Ledger device.</p>
				<p v-else>Ledger support is only available in the Chrome browser. Enable "Experimental Web Platform Features" in Chrome to connect to the Ledger device.</p>
			</div>
			<div class="create-wallet-button" @click="step = 'watch'">
				<div class="button-icon"><icon icon="eye" /></div>
				<div class="button-title">Watch-Only Wallet</div>
				<p>Creates a new watch-only wallet. Addresses must be added manually and transactions cannot be sent.</p>
			</div>
		</div>
		<div class="wallet-step" v-else-if="step === 'create'">
			<p>A new unique wallet seed will be generated and encrypted. It is important to save this
				seed in a secure location. You can use this seed to recover your funds
				from any device.</p>
			<div class="control">
				<label>Wallet Name</label>
				<input type="text" placeholder="Wallet" v-model="walletName" />
			</div>
			<div class="control" v-if="changeSeedType">
				<label>Seed Type</label>
				<select v-model="seedType">
					<option value="sia">Sia 29 word Seed</option>
					<option value="bip39">Walrus 12 word Seed</option>
				</select>
			</div>
			<div class="buttons">
				<button class="btn btn-success btn-inline" @click="onCreateWallet" :disabled="creating">Create</button>
			</div>
		</div>
		<div class="wallet-step" v-else-if="step === 'ledger' || step === 'watch'">
			<p v-if="step === 'ledger'">A new wallet will be created. Addresses must be manually
				imported from a connected Ledger device. Transactions must be signed by the same
				device. Only one hardware wallet can be created.</p>
			<p v-else-if="step === 'watch'">A new watch-only wallet will be created. addresses
				must be imported manually. Transactions cannot be created or broadcast.</p>
			<p v-else>A new unique 29 word wallet seed will be generated and encrypted. This seed
				should be saved in a secure location. You can use this seed to recover your funds from any Sia wallet.</p>
			<div class="control">
				<label>Wallet Name</label>
				<input type="text" placeholder="Wallet" v-model="walletName" />
			</div>
			<div class="controls">
				<button v-if="step === 'ledger'" class="btn btn-success btn-inline" @click="onCreateLedger">Import Addresses</button>
				<button v-else-if="step === 'watch'" class="btn btn-success btn-inline" @click="onCreateWatch">Import Addresses</button>
				<button v-else class="btn btn-success btn-inline" @click="onCreateWallet" :disabled="creating">Create</button>
			</div>
		</div>
		<div class="wallet-step" v-else-if="step === 'recover'" key="recover">
			<p>A new wallet will be created with the entered recovery seed. The blockchain will then
				be scanned for any transactions and funds owned by addresses generated by the seed.</p>
			<div class="control">
				<label>Wallet Name</label>
				<input type="text" placeholder="Wallet" v-model="walletName" />
			</div>
			<div class="control">
				<label>Recovery Seed</label>
				<textarea v-model="recoverySeed" />
			</div>
			<div class="controls">
				<button class="btn btn-success btn-inline" @click="onRecoverWallet" :disabled="creating">Recover</button>
			</div>
		</div>
		<div class="wallet-step" v-else-if="step === 'review'" key="review">
			<p>A new wallet has been created. Please backup your recovery seed to a safe location</p>
			<div class="control">
				<label>Recovery Seed</label>
				<textarea v-model="recoverySeed" readonly/>
			</div>
			<div class="controls">
				<button class="btn btn-success btn-inline" @click="walletCreated">Done</button>
			</div>
		</div>
		<import-ledger-addresses v-else-if="step === 'import-ledger'" key="ledger" :wallet="wallet" @imported="walletCreated" />
		<import-watch-addresses v-else-if="step === 'import-watch'" key="watch" :wallet="wallet" @imported="walletCreated" />
	</transition>
</template>

<script>
import { encode } from '@stablelib/base64';
import { mapState, mapActions } from 'vuex';
import { generateSeed, generateAddresses } from '@/utils/sia';
import { saveAddresses } from '@/store/db';
import { ledgerSupported } from '@/utils/ledger';

import ImportLedgerAddresses from '@/components/ledger/ImportLedgerAddresses';
import ImportWatchAddresses from '@/components/watch/ImportWatchAddresses';

export default {
	components: {
		ImportLedgerAddresses,
		ImportWatchAddresses
	},
	computed: {
		...mapState(['password', 'changeSeedType']),
		hardwareBtnClasses() {
			return {
				'create-wallet-button': true,
				'create-button-disabled': !this.ledgerSupported
			};
		},
		ledgerSupported() {
			return ledgerSupported();
		}
	},
	data() {
		return {
			creating: false,
			step: '',
			walletName: '',
			recoverySeed: '',
			seedType: 'sia',
			wallet: null
		};
	},
	mounted() {
		setTimeout(() => {
			this.step = 'pickMode';
		}, 300);
	},
	methods: {
		...mapActions(['createWallet']),
		async saveWallet(seed, type) {
			this.wallet = {
				seed,
				type,
				title: this.walletName || 'Wallet'
			};

			const id = await this.createWallet(this.wallet, this.password);

			this.wallet.id = id;
		},
		randomID() {
			const rand = new Uint8Array(64);

			window.crypto.getRandomValues(rand);

			return encode(rand);
		},
		onClickCreateHardware(step) {
			try {
				if (!ledgerSupported())
					return;

				this.step = step;
			} catch (ex) {
				console.error('onClickCreateHardware', ex);
			}
		},
		async onCreateLedger() {
			try {
				await this.saveWallet(this.randomID(), 'ledger');

				this.step = 'import-ledger';
			} catch (ex) {
				console.error('onCreateLedger', ex);
				this.pushNotification({
					severity: 'danger',
					message: ex.message
				});
			}
		},
		async onCreateWatch() {
			try {
				await this.saveWallet(this.randomID(), 'watch');

				this.step = 'import-watch';
			} catch (ex) {
				console.error('onCreateWatch', ex);
				this.pushNotification({
					severity: 'danger',
					message: ex.message
				});
			}
		},
		async onCreateWallet() {
			if (this.creating)
				return;

			this.creating = true;

			try {
				const seed = await generateSeed(this.seedType),
					addresses = await generateAddresses(seed, 0, 10);

				await this.saveWallet(seed, 'default');
				await saveAddresses(addresses.map(a => ({
					...a,
					wallet_id: this.wallet.id
				})));

				this.recoverySeed = seed;
				this.step = 'review';
			} catch (ex) {
				console.error('onCreateWallet', ex);
				this.pushNotification({
					severity: 'danger',
					message: ex.message
				});
			} finally {
				this.creating = false;
			}
		},
		async onRecoverWallet() {
			if (this.creating)
				return;

			this.creating = true;

			try {
				const addresses = await generateAddresses(this.recoverySeed, 0, 10);

				await this.saveWallet(this.recoverySeed, 'default');
				await saveAddresses(addresses.map(a => ({
					...a,
					wallet_id: this.wallet.id
				})));

				this.queueWallet(this.wallet.id, true);
				this.walletCreated();
			} catch (ex) {
				console.error('onRecoverWallet', ex);
				this.pushNotification({
					severity: 'danger',
					message: ex.message
				});
			} finally {
				this.creating = false;
			}
		},
		walletCreated() {
			this.pushNotification({
				message: 'New wallet created.'
			});
			this.$emit('created');
		}
	}
};
</script>

<style lang="stylus" scoped>
.header {
	padding: 15px;
	text-align: center;
	grid-column: 1 / -1;
}

.wallet-step {
	display: grid;
	height: 100%;
	width: 100%;
	padding: 15px;
	align-content: safe center;
	justify-content: center;

	textarea {
		height: 80px;
	}
}

p {
	font-size: 1.2rem;
	margin-bottom: 30px;
}

.wallet-mode {
	grid-gap: 20px;

	@media screen and (min-width: 767px) {
		grid-template-columns: repeat(2, minmax(0, 1fr));
	}
}

.divider {
	height: 1px;
	background: dark-gray;
	grid-column: 1 / -1;
}

.create-wallet-button {
	width: 100%;
	padding: 15px;
	border: 1px solid dark-gray;
	border-radius: 4px;
	box-shadow: 0 1px 2px 1px rgba(0, 0, 0, 0.14);
	transition: all 0.3s linear;

	&.create-button-disabled {
		opacity: 0.54;

		&:focus, &:active, &:hover {
			color: rgba(255, 255, 255, 0.54);
			border-color: dark-gray;
			cursor: pointer;
			box-shadow: 0 1px 2px 1px rgba(0, 0, 0, 0.28);
		}
	}

	.button-icon {
		font-size: 2.4rem;
		text-align: center;
		margin-bottom: 15px;
	}

	.button-title {
		font-size: 1.2rem;
		text-align: center;
		margin-bottom: 15px;
	}

	p {
		color: rgba(255, 255, 255, 0.54);
		margin: 0;
	}

	&:focus, &:active, &:hover {
		color: primary;
		border-color: primary;
		cursor: pointer;
		box-shadow: 0 1px 2px 1px rgba(0, 0, 0, 0.28);
	}
}

.controls {
	text-align: center;

	button {
		margin: 0;
	}
}
</style>